channels:
  - conda-forge
dependencies:
  - appmode
  - numpy
  - pandas
  - pandas-profiling
  - altgraph
  - beautifulsoup4
  - brotlipy
  - bs4
  - build
  - certifi
  - click
  - cycler
  - docutils
  - entrypoints
  - finVizFetchPkg
  - future
  - jedi
  - joblib
  - json5
  - keyring
  - kiwisolver
  - MarkupSafe
  - matplotlib
  - #menuinst
  - mistune
  - nltk
  - numpy
  - olefile
  - pandas
  - pefile
  - pep517
  - pkginfo
  - pycosat
  - PyYAML
  - pyzmq
  - QtPy
  - readme-renderer
  - regex
  - requests-toolbelt
  - rfc3986
  - ruamel-yaml
  - sentimentAnalysisPkg
  - soupsieve
  - terminado
  - toml
  - twine
  - webencodings
  - wincertstore
  - wordcloud
  - xmltodict
 

  
  
  
  
  
  
