channels:
  - conda-forge
  - defaults
dependencies:
  - appmode
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - beautifulsoup4
  - finVizFetchPkg
  - sentimentAnalysisPkg
